name: E2E tests
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    env:
      LOKI_TENANT_ID: ${{ secrets.LOKI_TENANT_ID }}
      LOKI_BASIC_AUTH: ${{ secrets.LOKI_BASIC_AUTH }}
      LOKI_URL: ${{ secrets.LOKI_URL }}
    runs-on: ubuntu20.04-8cores-32GB
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run tests
        run: |-
          nix develop -c make test_loki
